### ISSUE TITLE
Expo prebuild fails — “Cannot find module './lib/commonjs/expo'”

### ISSUE THREAD

**Issue by gpadova** [callstackincubator/react-native-bottom-tabs#450]
### Before submitting a new issue

- [x] I tested using the latest version of the library, as the bug might be already fixed.
- [x] I tested using a [supported version](https://github.com/reactwg/react-native-releases/blob/main/docs/support.md) of react native.
- [x] I checked for possible duplicate issues, with possible answers.

### Bug summary

Bug: Expo prebuild fails — “Cannot find module './lib/commonjs/expo'”

Description

When adding the react-native-bottom-tabs plugin to the Expo config (plugins array in app.config.ts), the expo prebuild command fails with the following error:

	Error: Cannot find module './lib/commonjs/expo'
	Require stack:
	- node_modules/react-native-bottom-tabs/app.plugin.js
	...

After inspecting node_modules/react-native-bottom-tabs, it seems the published package on npm is missing the compiled lib/commonjs/expo directory, which app.plugin.js tries to require.

📦 Investigation

Inside node_modules/react-native-bottom-tabs, the file app.plugin.js contains:

	module.exports = require('./lib/commonjs/expo');

However, the package does not include a lib/commonjs directory — it appears the CommonJS build artifacts were not published to npm.

This causes Expo’s config plugin resolver to crash when running expo prebuild.

---

💡 Expected Behavior

expo prebuild should resolve the app.plugin.js normally and complete without errors.

The package should include the built /lib/commonjs/expo.js file in the npm tarball.

### Library version

1.0.0

### Environment info

```shell
- react-native-bottom-tabs version: 1.0.0 

- Expo SDK: 53

- Node: 22

- OS: macOS

- Prebuild command: npx expo prebuild
```

### Steps to reproduce

1. Install the package:

	npm install react-native-bottom-tabs

2. Add it to your app.config.ts:

	plugins: [
	  'react-native-bottom-tabs',
	  // other plugins...
	],
3. Run:

	npx expo prebuild

4. Observe the error:

	Error: Cannot find module './lib/commonjs/expo'

### Reproducible sample code

```js
Using react-native-bottom-tabs as an Expo config plugin causes the prebuild process to crash because the published package is missing its compiled CommonJS output.

Error output

	Error: Cannot find module './lib/commonjs/expo'
	Require stack:
	- node_modules/react-native-bottom-tabs/app.plugin.js
	- @expo/config-plugins/build/utils/plugin-resolver.js
	- @expo/cli/build/src/prebuild/prebuildAsync.js
	...

Opening the installed package confirms that the lib/commonjs/expo.js file doesn’t exist, even though it’s required by app.plugin.js.

cmd: ls node_modules/react-native-bottom-tabs/lib/commonjs
ls: node_modules/react-native-bottom-tabs/lib/commonjs: No such file or directory
```

**Comment by dennisnjd** [comment]
I ran into the same issue after upgraded the library's version to 1.0.0.
The solution worked for me is bit strange , that I just commented the ''react-native-bottom-tabs" in plugins , and everything worked fine.
After tested, I found no issues with the navigation without the plugin. But I don't believe it is the proper solution.

**Comment by mrzhiin** [comment]
> > Hi, I think the issue is still there with 1.0.1.
> > On expo prebuild it gives the error : "SyntaxError: The requested module '@expo/config-plugins' does not provide an export named 'createRunOncePlugin"
> > <img alt="Image" width="1062" height="276" src="https://private-user-images.githubusercontent.com/66307217/503485965-46b08281-95b5-487e-8d52-8e69afb7dea1.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjEwMjUyMzksIm5iZiI6MTc2MTAyNDkzOSwicGF0aCI6Ii82NjMwNzIxNy81MDM0ODU5NjUtNDZiMDgyODEtOTViNS00ODdlLThkNTItOGU2OWFmYjdkZWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDIxVDA1MzUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZmI1ZmYyNWUyOWI2YWQ2ZjJkMzhjYWUxNjhlNTIxNzUxNGE0ODdiNjcwNjkyNWEzYTFiZjJkZmIyOTkwNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.GDvAE0TARbfCAcmTKFAJVqxJUAM2i231LEApu_fvok8">
> 
> Do you use Expo54?

I am using Expo 54.0.15 had same error
